### PR TITLE
Added prop to add thumbnails

### PR DESCRIPTION
**Pull request by Ovi**

### CODE REVIEW

**Review by kashifsulaiman — CHANGES_REQUESTED** [review]
Thank you so much @Ovi for the PR.
Just a thing, what if we go for making the `images` prop an array of objects so in this way a developer will not separate thumbnails from the images.  Usually, we store our data in database in this format

```
images: [{imageUrl: 'someUrl.jpg', thumbnailUrl: 'thumbUrl.jpg'}, {imageUrl: 'someUrl.jpg', thumbnailUrl: 'thumbUrl.jpg'}]
```

What do you think?

**Comment by Ovi** [comment]
That's a pretty good idea, but what if someone only wanted to provide images - not thumbnails, (as thumbnails are just optional) so he would have to make an array of objects just for image urls in order to provide images.

**Comment by kashifsulaiman** [comment]
> That's a pretty good idea, but what if someone only wanted to provide images - not thumbnails, (as thumbnails are just optional) so he would have to make an array of objects just for image urls in order to provide images.

Yes that's a point, but we can manage it on our end.
We'll allow user to post only an array of string for the images only (as in the current version)
or allow user to post array of objects (with or without thumbUrl).
So we can have check, that is it array of objects or strings and then workout accordingly.

**Comment by Ovi** [comment]
Yes, we can work on this idea!

**Comment by Ovi** [comment]
Will make a new PR with updated things!

**Pull request closed without merging**
